name: .NET CI Heroku

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/IT.Identity.sln
    - name: Build
      run: dotnet build --no-restore ./src/IT.Identity.sln
  
  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:src"
        file: ./InvesTrace.Identity.Api/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/it-identity-development:latest
        build-args: |
          ENVIRONMENT=Development

  deploy:
    name: Deploy into Heroku Account
    runs-on: ubuntu-latest
    needs: docker

    environment: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Build Docker image
      - name: Docker build
        env: 
          HEROKU_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: docker login --username=_ --password=$HEROKU_KEY registry.heroku.com

      - name: Heroku login credentials
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          sudo apt update && sudo apt install heroku
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF

      # Push the Docker image to Heroku Container Registry
      - name: Publish
        env: 
          HEROKU_NAME: ${{ secrets.HEROKU_API_NAME }}
        run: |
          heroku container:push web --recursive -a $HEROKU_NAME --context-path src/InvesTrace.Identity.Api --args ENVIRONMENT=Development
          heroku container:release web --recursive -a $HEROKU_NAME --context-path src/InvesTrace.Identity.Api --args ENVIRONMENT=Development
      
      # - name: Deploying into Heroku
      #   uses: AkhileshNS/heroku-deploy@v3.13.15
      #   with:
      #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      #     heroku_app_name: ${{ secrets.HEROKU_API_NAME }}
      #     heroku_email: ${{ secrets.HEROKU_EMAIL }}
      #     #usedocker: true
      #     docker_build_args: |
      #       ENVIRONMENT=Development
      #     appdir: "src/InvesTrace.Identity.Api/"
      # - name: Docker Pull Image
      #   run: | 
      #       docker pull ${{ secrets.DOCKERHUB_USERNAME }}/it-identity-development:latest && 
      #       id=`docker images | grep $docker_image | awk '{print $3}'` &&
      #       docker tag $id registry.heroku.com/${{ secrets.HEROKU_API_NAME }}/web &&
      #       docker push registry.heroku.com/${{ secrets.HEROKU_API_NAME }}/web
