name: .NET CI Heroku

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/IT.Identity.sln
    - name: Build
      run: dotnet build --no-restore ./src/IT.Identity.sln
  
  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./src/InvesTrace.Identity.Api/Dockerfile
        push: true
        tags: gabrieljunio/finance-api:latest

  deploy:
    name: Deploy into Heroku Account
    runs-on: ubuntu-latest
    needs: docker

    environment: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with: 
          files: '**/appsettings.json'
        env:
          AppSettings: ${{ secrets.APP_SETTINGS }}
      - name: Deploying into Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_API_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true